services:
  workout-storage:
    image: mysql:latest
    container_name: workout-storage
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./WorkoutService/data/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Welkom32!"

  workout-service:
    image: workout-service:latest
    container_name: workout-service
    ports:
      - "8080:80"

  user-storage:
    image: mysql:latest
    container_name: user-storage
    ports:
      - "3307:3306"
      - "33070:33060"
    volumes:
      - ./UserService/data/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Welkom32!"

  user-service:
    image: user-service:latest
    container_name: user-service
    ports:
      - "8081:80"

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: Welkom32!
