apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service-deployment
  labels:
    app: workout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: app
          image: lexfuny/workout-service:master
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service-service
spec:
  ports:
    - name: 'http'
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: workout-service
